#!/usr/bin/python
import spidev
import time
import RPi.GPIO as GPIO

import csv
import random

GPIO.setmode(GPIO.BCM)

#Open SPI bus
spi = spidev.SpiDev()
spi.open(0,0)
spi.max_speed_hz=1000000



#define custom chip select
#this is done so we can use dozens of SPI devices on 1 bus
CS_ADC = 12
GPIO.setup(CS_ADC, GPIO.OUT)

# Function to read SPI data from MCP3008 chip
# Channel must be an integer 0-7
def ReadChannel3008(channel):
  #below sends 00000001 1xxx0000 00000000 to the chip and records the response
  #xxx encodes 0-7, the channel selected for the transfer.
  adc = spi.xfer2([1,(8+channel)<<4,0])
  data = ((adc[1]&3) << 8) + adc[2]
  return data

#same thing but for the 12-bit MCP3208
def ReadChannel3208(channel):
  adc = spi.xfer2([6|(channel>>2),channel<<6,0]) #0000011x,xx000000,00000000
  data = ((adc[1]&15) << 8) + adc[2]
  return data

def ConvertToVoltage(value, bitdepth, vref):
  return vref*(value/(2**bitdepth-1))

# Define delay between readings
delay = 0.005

x_value = 0
voltage_1 = 0
voltage_2 = 0

fieldnames = ["x_value", "voltage_1", "voltage_2", "voltage_3"]

with open('data.csv', 'w') as csv_file:
    csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    csv_writer.writeheader()
 
while True:

    GPIO.output(CS_ADC, GPIO.LOW)
    value1 = ReadChannel3208(3)
    value2 = ReadChannel3208(4)
    value3 = ReadChannel3208(5)
    GPIO.output(CS_ADC, GPIO.HIGH)
    voltage1 = ConvertToVoltage(value1, 12, 3.3) #for MCP3208 at 3.3V
    voltage2 = ConvertToVoltage(value2, 12, 3.3) #for MCP3208 at 3.3V
    voltage3 = ConvertToVoltage(value3, 12, 3.3) #for MCP3208 at 3.3V
    #print(value)
    #print(f"{voltage:.3f}")
    # Wait before repeating loop
  
    with open('data.csv', 'a') as csv_file:
            csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)                    
                        
            voltage_1 = f"{voltage1:.3f}" #total_1 + random.randint(-6, 8)
            voltage_2 = f"{voltage2:.3f}" #total_2 + random.randint(-5, 6)
            voltage_3 = f"{voltage3:.3f}" #total_2 + random.randint(-5, 6) 
            x_value += 1
            
            info = {
                "x_value": x_value,
                "voltage_1": voltage_1,
                "voltage_2": voltage_2,
                "voltage_3": voltage_3
            }
            csv_writer.writerow(info)
            print(x_value, voltage_1, voltage_2, voltage_3)
      
    time.sleep(delay)


